on:
  workflow_dispatch:

name: Manual

jobs:
  checks:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Output
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            console.log(context.inputs)
      - name: Summary
        run: |
          echo "## Foo" >> $GITHUB_STEP_SUMMARY
          echo "## Bar" >> $GITHUB_STEP_SUMMARY
          echo "## Baz" >> $GITHUB_STEP_SUMMARY
      - uses: WcAServices/markdown-template-action@v1.0.2
        with:
          # These will be injected into the below template, in addition to GitHub's standard
          # variables. You can perform string operations here as well.
          variables: >-
            GREETING="world"
            COMMIT_SHA="${{ github.sha }}"
            SHORT_SHA=${COMMIT_SHA:0:7}

          # The following language="..." comment enables syntax highlighting in JetBrains IDEs

          # language="markdown"
          template: |
            # Hello, $GREETING
            > ### You're on commit [`$SHORT_SHA`]($COMMIT_SHA)

            ##### Standard GitHub variables should work too:
            ```yaml
            Github Ref: $GITHUB_REF
            Commit author: $GITHUB_ACTOR
            Job: $GITHUB_JOB
            ```
