on:
  push:
    branches:
      - main

name: reuse

env:
  SERVICE_NAME: ${{ vars.SERVICE_NAME || 'default' }}

jobs:
  generate-variables:
    name: generate-variables
    runs-on: ubuntu-latest

    outputs:
      IMAGE_TAG: ${{ env.image_tag }}
      DOCKER_TAGS: ${{ steps.meta.outputs.tags }}

    steps:
    - name: Get current branch name
      id: branch-name
      uses: tj-actions/branch-names@v8

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/coachhubio/ch-sre.${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}
        tags: |
          type=sha

    # - name: Generate Image tag
    #   run: |
    #     TAGS=${{ steps.meta.outputs.tags }}
    #     IMAGE_TAG=$(echo $TAGS | sed 's/.*\(...........\)/\1/')
    #     echo image_tag=$IMAGE_TAG >> "$GITHUB_ENV"

    # - uses: WcAServices/markdown-template-action@v1
    #   with:
    #     template: |
    #       # Deploying development and staging environment
    #       ```yaml
    #       Github Ref: $GITHUB_REF
    #       Commit author: $GITHUB_ACTOR
    #       Docker Image Tag: ${{ env.image_tag }}
    #       Branch: ${{ steps.branch-name.outputs.current_branch }}
    #       ----
    #       commit User Name: ${{ github.event.pusher.name }}
    #       commit User Email: ${{ github.event.pusher.email }}

    - name: Output
      uses: actions/github-script@v7
      with:
        script: |
          console.log(context)

  testing-retrieve:
    name: Testing var retrieval
    runs-on: ubuntu-latest
    needs: ["generate-variables"]

    env:
      IMAGE_TAG: ${{ needs.generate-variables.outputs.IMAGE_TAG }}
      DOCKER_TAGS: ${{ needs.generate-variables.outputs.DOCKER_TAGS }}

    steps:
      - run: |
          printenv

      - uses: WcAServices/markdown-template-action@v1
        with:
          template: |
            # Outputing the docker image tag computed by `docker/metadata-action@v5`

            ```yaml
            docker_tag: ${{ env.DOCKER_TAGS }}
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_TAGS }}
